replicaCount: 1

image:
  repository: ghcr.io/dgmndoo/mnd-web-deploy
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 8080
  nodePort: 30080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {} 