apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mondoo-web
  labels:
    app: mondoo-web
    {{- include "mondoo-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mondoo-web
      {{- include "mondoo-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: mondoo-web
        {{- include "mondoo-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 