apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mondoo-web
  labels:
    {{- include "mondoo-web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: mondoo-web
    {{- include "mondoo-web.selectorLabels" . | nindent 4 }} 