name: Build and Push Docker Image

on:
  repository_dispatch:
    types: [release_created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPO_NAME: dgmndoo/mnd-challenge

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download release binary
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          RELEASE_INFO=$(curl -L \
            -H "Accept: application/json" \
            -H "Authorization: token $GH_TOKEN" \
            "https://api.github.com/repos/${{ env.REPO_NAME }}/releases/tags/${{ github.event.client_payload.release_tag }}")
          
          DOWNLOAD_URL=$(echo "$RELEASE_INFO" | jq -r '.assets[] | select(.name | endswith("-linux-amd64")) | .browser_download_url')
          
          curl -L \
            -H "Authorization: token $GH_TOKEN" \
            -o ./mondoo-web/server \
            "$DOWNLOAD_URL"

          chmod +x ./mondoo-web/server

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.client_payload.release_tag }}
            type=raw,value=latest

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mondoo-web
          file: ./mondoo-web/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true

      - name: Run container
        run: |
          IMAGE_TAG=$(docker images --no-trunc --quiet ${{ steps.meta.outputs.tags }} | head -n 1)
          docker run -d --name my_container $IMAGE_TAG

      - name: Install cnspec
        run: |
          bash -c "$(curl -sSL https://install.mondoo.com/sh)"

      - name: Verify Docker image with cnspec
        run: |
          CONTAINER_SHA=$(docker ps -q | head -n1)
          cnspec scan docker container $CONTAINER_SHA \
            -f ./mondoo-web/policy/webapp.mql.yaml --score-threshold 50
      
      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: ./mondoo-web
          file: ./mondoo-web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 